#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Gu Wu Test Gap Display - Read and display Feng Shui test gap recommendations

Purpose: Display test coverage gaps identified by Feng Shui orchestrator
Usage: Called by Gu Wu tools to show actionable test recommendations

Integration: Part of Feng Shui → Gu Wu communication bridge
Reads: .fengshui_test_gaps.json (generated by pre_commit_orchestrator.py)
"""

import sys
import json
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

# Windows encoding fix
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Get project root
PROJECT_ROOT = Path(__file__).parent.parent.parent
GAP_REPORT_FILE = PROJECT_ROOT / '.fengshui_test_gaps.json'


def load_test_gaps() -> Optional[Dict]:
    """Load test gap report from Feng Shui"""
    if not GAP_REPORT_FILE.exists():
        return None
    
    try:
        content = GAP_REPORT_FILE.read_text(encoding='utf-8')
        return json.loads(content)
    except Exception as e:
        print(f"[WARNING] Failed to load test gap report: {e}")
        return None


def format_timestamp(iso_timestamp: str) -> str:
    """Format ISO timestamp to human-readable string"""
    try:
        dt = datetime.fromisoformat(iso_timestamp.replace('Z', '+00:00'))
        return dt.strftime('%Y-%m-%d %H:%M:%S UTC')
    except:
        return iso_timestamp


def display_test_gaps(verbose: bool = False):
    """Display test coverage gaps in human-readable format"""
    report = load_test_gaps()
    
    if not report:
        print("\n[GU WU] No test gaps detected")
        print("=" * 60)
        print("[INFO] Feng Shui has not identified any test coverage gaps")
        print("[TIP] Stage files and commit to trigger gap analysis")
        print("=" * 60)
        return
    
    # Extract report data
    timestamp = report.get('timestamp', 'Unknown')
    commit_context = report.get('commit_context', {})
    test_gaps = report.get('test_gaps', [])
    summary = report.get('summary', {})
    
    # Display header
    print("\n[GU WU] Test Coverage Gaps Report")
    print("=" * 60)
    print(f"[GENERATED] {format_timestamp(timestamp)}")
    print(f"[CONTEXT] {commit_context.get('staged_files_count', 0)} staged file(s)")
    print("")
    
    if not test_gaps:
        print("[OK] No test gaps found!")
        print("=" * 60)
        return
    
    # Display summary
    print("[SUMMARY]")
    print(f"  Total Gaps: {summary.get('total_gaps', 0)}")
    print(f"  High Severity: {summary.get('high_severity', 0)}")
    print(f"  Medium Severity: {summary.get('medium_severity', 0)}")
    print(f"  Low Severity: {summary.get('low_severity', 0)}")
    print("")
    
    # Display gaps grouped by severity
    high_gaps = [g for g in test_gaps if g.get('severity') == 'HIGH']
    medium_gaps = [g for g in test_gaps if g.get('severity') == 'MEDIUM']
    low_gaps = [g for g in test_gaps if g.get('severity') == 'LOW']
    
    if high_gaps:
        print("[🔴 HIGH PRIORITY GAPS]")
        print("=" * 60)
        for i, gap in enumerate(high_gaps, 1):
            display_gap(i, gap, verbose)
        print("")
    
    if medium_gaps:
        print("[⚠️  MEDIUM PRIORITY GAPS]")
        print("=" * 60)
        for i, gap in enumerate(medium_gaps, 1):
            display_gap(i, gap, verbose)
        print("")
    
    if low_gaps and verbose:
        print("[ℹ️  LOW PRIORITY GAPS]")
        print("=" * 60)
        for i, gap in enumerate(low_gaps, 1):
            display_gap(i, gap, verbose)
        print("")
    
    # Display next actions
    print("[NEXT ACTIONS]")
    print("=" * 60)
    print("1. Review gaps above and prioritize HIGH severity first")
    print("2. Create missing test files using Gu Wu generator:")
    print("   python -m tools.guwu.generators.test_generator <source_file>")
    print("3. Run tests to verify: pytest tests/unit/...")
    print("4. Commit again to re-validate")
    print("")
    print("[TIP] Use --auto-generate flag to create test stubs automatically")
    print("=" * 60)
    print("")


def display_gap(index: int, gap: Dict, verbose: bool):
    """Display a single test gap"""
    file = gap.get('file', 'Unknown')
    gap_type = gap.get('gap_type', 'Unknown')
    severity = gap.get('severity', 'UNKNOWN')
    details = gap.get('details', '')
    recommendation = gap.get('recommendation', '')
    
    severity_icon = {
        'HIGH': '🔴',
        'MEDIUM': '⚠️',
        'LOW': 'ℹ️'
    }.get(severity, '?')
    
    print(f"{severity_icon} Gap #{index}: {file}")
    print(f"   Type: {gap_type}")
    print(f"   Details: {details}")
    print(f"   Recommendation: {recommendation}")
    
    if verbose and gap.get('suggested_test_file'):
        print(f"   Suggested Test File: {gap['suggested_test_file']}")
    
    print("")


def generate_test_stubs(gap_report_path: Optional[Path] = None) -> bool:
    """
    Generate test stub files for detected gaps
    
    Returns:
        True if stubs generated successfully
    """
    report = load_test_gaps()
    
    if not report:
        print("[ERROR] No test gap report found")
        return False
    
    test_gaps = report.get('test_gaps', [])
    
    if not test_gaps:
        print("[INFO] No test gaps to generate stubs for")
        return True
    
    # Filter gaps that need new test files
    missing_test_files = [
        g for g in test_gaps 
        if g.get('gap_type') == 'missing_test_file'
    ]
    
    if not missing_test_files:
        print("[INFO] No missing test files (all gaps are coverage-related)")
        return True
    
    print(f"\n[GU WU] Generating test stubs for {len(missing_test_files)} file(s)...")
    print("=" * 60)
    
    generated = []
    skipped = []
    
    for gap in missing_test_files:
        source_file = gap.get('file')
        test_file = gap.get('recommendation', '').replace('Create ', '')
        
        if not test_file or not source_file:
            skipped.append(source_file)
            continue
        
        # Generate test stub
        success = create_test_stub(source_file, test_file)
        
        if success:
            generated.append(test_file)
            print(f"✅ Created: {test_file}")
        else:
            skipped.append(source_file)
            print(f"❌ Failed: {test_file}")
    
    print("=" * 60)
    print(f"[RESULT] Generated {len(generated)} test file(s)")
    
    if skipped:
        print(f"[SKIPPED] {len(skipped)} file(s) (see errors above)")
    
    print("")
    return len(skipped) == 0


def create_test_stub(source_file: str, test_file: str) -> bool:
    """Create a test stub file with basic structure"""
    test_path = PROJECT_ROOT / test_file
    
    # Don't overwrite existing files
    if test_path.exists():
        return False
    
    # Create directories if needed
    test_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Get module name for import
    source_path = Path(source_file)
    module_name = source_path.stem
    
    # Determine import path
    # modules/data_products_v2/backend/api.py → modules.data_products_v2.backend.api
    import_path = str(source_path.with_suffix('')).replace('/', '.')
    
    # Generate test stub content
    stub_content = f'''"""
Unit tests for {source_file}

Generated by Gu Wu Test Gap Bridge
"""

import pytest
from {import_path} import *


@pytest.mark.unit
class Test{module_name.title().replace('_', '')}:
    """Test suite for {module_name}.py"""
    
    def test_placeholder(self):
        """
        TODO: Replace with actual tests
        
        This is a stub generated by Gu Wu. Add your test cases here.
        Follow AAA pattern: Arrange, Act, Assert
        """
        # ARRANGE
        # Setup test data and dependencies
        
        # ACT
        # Execute the code being tested
        
        # ASSERT
        # Verify the results
        pass


# TODO: Add more test cases
# - Test happy path scenarios
# - Test error handling
# - Test edge cases
# - Test boundary conditions
'''
    
    try:
        test_path.write_text(stub_content, encoding='utf-8')
        return True
    except Exception as e:
        print(f"   Error creating {test_file}: {e}")
        return False


def main():
    """Main entry point for test gap display"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Display test coverage gaps from Feng Shui'
    )
    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Show all gaps including low priority'
    )
    parser.add_argument(
        '--auto-generate',
        action='store_true',
        help='Automatically generate test stub files'
    )
    
    args = parser.parse_args()
    
    # Display gaps
    display_test_gaps(verbose=args.verbose)
    
    # Auto-generate stubs if requested
    if args.auto_generate:
        generate_test_stubs()


if __name__ == '__main__':
    main()