-- ============================================
-- SAP HANA Cloud P2P User Creation
-- Execute as DBADMIN in Database Explorer
-- ============================================

-- Step 1: Create User
CREATE USER P2P_DEV_USER PASSWORD "P2P_Dev123!";

-- Step 2: Force password change on first login
ALTER USER P2P_DEV_USER FORCE FIRST PASSWORD CHANGE;

-- Step 3: Add comment
COMMENT ON USER P2P_DEV_USER IS 'P2P Development User - Procure-to-Pay Project';

-- Step 4: Grant System Privileges
GRANT CREATE SCHEMA TO P2P_DEV_USER;
GRANT IMPORT TO P2P_DEV_USER;
GRANT EXPORT TO P2P_DEV_USER;
GRANT CATALOG READ TO P2P_DEV_USER;

-- Step 5: Create P2P Schema
CREATE SCHEMA P2P_SCHEMA OWNED BY P2P_DEV_USER;

-- Step 6: Grant Schema Privileges (11 individual grants for BDC compatibility)
GRANT ALTER ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT CREATE ANY ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT DELETE ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT DROP ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT EXECUTE ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT INDEX ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT INSERT ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT REFERENCES ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT SELECT ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT TRUNCATE ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;
GRANT UPDATE ON SCHEMA P2P_SCHEMA TO P2P_DEV_USER WITH GRANT OPTION;

-- Step 7: Set Default Schema
ALTER USER P2P_DEV_USER SET PARAMETER SCHEMA = 'P2P_SCHEMA';

-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check user was created
SELECT USER_NAME, CREATOR, CREATE_TIME 
FROM SYS.USERS 
WHERE USER_NAME = 'P2P_DEV_USER';

-- Check privileges granted
SELECT GRANTEE, PRIVILEGE, SCHEMA_NAME, IS_GRANTABLE
FROM SYS.GRANTED_PRIVILEGES
WHERE GRANTEE = 'P2P_DEV_USER'
AND SCHEMA_NAME = 'P2P_SCHEMA'
ORDER BY PRIVILEGE;

-- Check schema ownership
SELECT SCHEMA_NAME, SCHEMA_OWNER
FROM SYS.SCHEMAS
WHERE SCHEMA_NAME = 'P2P_SCHEMA';

-- ============================================
-- SUCCESS! 
-- User: P2P_DEV_USER
-- Password: P2P_Dev123! (must change on first login)
-- Schema: P2P_SCHEMA
-- ============================================
