"""
Base Test Generator

Abstract class for all test generators.
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Dict, Any
from datetime import datetime


class BaseTestGenerator(ABC):
    """
    Base class for test generators
    
    Subclasses generate pytest tests from Feng Shui reports.
    """
    
    def __init__(self, output_dir: Path = None):
        """
        Initialize generator
        
        Args:
            output_dir: Directory to write generated tests (default: tests/e2e/app_v2/)
        """
        self.output_dir = output_dir or Path("tests/e2e/app_v2")
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    @abstractmethod
    def generate_from_report(self, report: Dict[str, Any]) -> Path:
        """
        Generate pytest tests from Feng Shui report
        
        Args:
            report: Feng Shui validation report (JSON dict)
            
        Returns:
            Path to generated test file
        """
        pass
    
    def _generate_test_header(self, module_name: str) -> str:
        """Generate standard pytest test file header"""
        return f'''"""
Auto-generated E2E tests for {module_name}

Generated by: Gu Wu (顾武) Test Generator
Source: Feng Shui (风水) Multi-Agent Analysis
Date: {datetime.now().isoformat()}

DO NOT EDIT - Regenerate from Feng Shui report if validation changes.
"""

import pytest
from pathlib import Path
import json


# Module under test
MODULE_NAME = "{module_name}"
MODULE_PATH = Path(f"modules/{{MODULE_NAME}}")

'''
    
    def _generate_test_footer(self) -> str:
        """Generate standard test file footer"""
        return """

if __name__ == '__main__':
    pytest.main([__file__, '-v'])
"""